server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: movie-service
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3370/movie-dev
    username: usr-movie
    password: pwd-movie
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  zipkin:
    base-url: http://localhost:9411/
    enabled: true

queue:
  movie:
    name: movie-queue

management:
  endpoints:
    web:
      exposure:
        include: info
  info:
    env:
      enabled: true
  endpoint:
    info:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: microservice registration
  svc:
    #    intanceid: ${eureka.instance.instance-id}
    port: ${server.port}


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true